media:
  input: assets
  output: assets

content:
  - name: site_content
    label: Edit Website
    type: file
    path: content.json
    format: json
    fields:
      - name: businessName
        label: Business Name
        type: string

      - name: subtitle
        label: Subtitle
        type: string

      - name: email
        label: Email Address
        type: string

      - name: services
        label: GIS Services
        type: object
        list: true
        fields:
          - name: title
            label: Service Name
            type: string

          - name: description
            label: Service Description
            type: text